project:
  type: website

website:
  title: "WhatTown"
  navbar:
    left:
      - href: index.qmd
        text: Proposal

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

