project:
  type: website

website:
  title: "WhatTown"
  navbar:
    left:
      - href: index.qmd
        text: Overview
        
      - text: "Prototypes"
        menu:
          - text: "Accessibility Prototype"
            href: prototypes/Accessibility Prototype.html
      - text: "Data Wrangling"
        menu: 
          - text: "Point Geometry Wrangling"
            href: prototypes/PointWrangling.html
          - text: "Accessibility Geometry Wrangling"
            href: prototypes/AccessibilityGeometryWrangling.html
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

