project:
  type: website

website:
  title: "WhatTown"
  navbar:
    left:
      - href: index.qmd
        text: Proposal
        
      - text: "Prototypes"
        menu:
          - text: "Accessibility Prototype"
            href: prototypes/Accessibility Prototype.html
format:
  html:
    theme: yeti
    css: styles.css
    toc: true

editor: visual

